spring:
  application:
    name: RATING-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ratingservice
    url: jdbc:postgresql://localhost:5432/ratingservice
    username: ratingservice
    hikari:
      schema: ratingservice
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka